### ISSUE TITLE
web界面

### ISSUE THREAD

**Issue by hunao0221** [okhelperTeam/okhelper-web#1]
请问只是适配了手机端H5界面吗？

**Comment by zxadgithub** [comment]
对的，，后端api是完善的，前段只有手机web，也可以打包成app。可以自己对接别的。 在2018年07月27日 14:24，胡闹 写道： 请问只是适配了手机端H5界面吗？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by wht1992** [comment]
你好  运行npm run dev后访问localhost:8080 显示空白

**Comment by return-stay** [comment]
请问一直报401是什么原因，注册页都会报401？
