### ISSUE TITLE
UserServiceImpl.java 414行存储 token 的时候  是不是应该是 token?

### ISSUE THREAD

**Issue by insomniatt** [okhelperTeam/okhelper-web#3]
String secret = PasswordHelp.passwordSalt(user.getUserName(), user.getUserPassword());

        //如果一小时内过期，补签Token
        if (expiresAt != null && date.after(expiresAt)) {
            String token = JWTUtil.sign(user.getId(), user.getUserName(), secret, user.getStoreId());
414//            userVo.setToken(secret);
        }

**Comment by zxadgithub** [comment]
对

Tao Ju <notifications@github.com> 于2018年9月15日周六 下午2:08写道：
